.github/ISSUE_TEMPLATE

Closes https://github.com/entropyxyz/entropy-docs/issues/119

Moves issue description to top in issue template.

---

docs/basics/quickstart.md
docs/guides/manage-accounts.md

Addresses issue from https://github.com/entropyxyz/community/discussions/68.
Updates the account workflow to match the latest CLI release.

Updates account workflow to match CLI.

---

docusaurus.config.js

Closes https://github.com/entropyxyz/entropy-docs/issues/143

Adds Plausible script into docusaurus config.

---

docs/guides/deploy-a-program.md
docs/guides/register-an-account.md
sidebars.js

Closes https://github.com/entropyxyz/entropy-docs/issues/55

Adds "deploy programs" guide.

---

content/reference/cli.md

Closes https://github.com/entropyxyz/entropy-docs/issues/171
Closes https://github.com/entropyxyz/entropy-docs/issues/172

Adds in-line commands to CLI reference docs.

---

content/basics/entrosplainer.md

Closes https://github.com/entropyxyz/entropy-docs/issues/176

Re-adds missing images.

---

content/reference/cli.md

Adds some nice little cards at the top of the CLI reference page to sort folks to the correct section.
Also improves and updates examples in Programmatic Mode section.

Improves readability, adds cards to sections.

---

content/basics/entrosplainer.md

Closes https://github.com/entropyxyz/entropy-docs/issues/163

Adds math functionality to Entrosplainer.

---

hugo.yaml
themes/hextra/layouts/partials/scripts.html

Closes https://github.com/entropyxyz/entropy-docs/issues/179

Adds Plausible into site.

---

content/guides/deploy-a-program.md
content/guides/manage-accounts.md
content/guides/register-an-account.md
content/guides/transfer-funds.md

Closes https://github.com/entropyxyz/entropy-docs/issues/185

Updates existing guides with TUI process.

---

content/concepts/programs.md

Closes https://github.com/entropyxyz/entropy-docs/issues/187

Adds an easier-to-understand intro to Programs

---

content/_index.md
hugo.yaml
themes/hextra/assets/css/custom.css

Closes https://github.com/entropyxyz/entropy-docs/issues/188

Make the purpose of Entropy clear from the beginning.

---

content/guides/manage-accounts.md

Closes https://github.com/entropyxyz/entropy-docs/issues/186

Updates TUI header to match the rest of docs.

---

themes/hextra/assets/css/custom.css

Closes https://github.com/entropyxyz/entropy-docs/issues/158

Hides copy button in cmd outputs.

---

content/concepts/programs.md

Closes https://github.com/entropyxyz/entropy-docs/issues/200

Add description and explanation for device-proxy program.

---

README.md
content/basics/quickstart.md
themes/hextra/layouts/shortcodes/tooltip.html

Closes https://github.com/entropyxyz/entropy-docs/issues/160

Adds `tooltip` shortcode.

---

content/reference/tools.md

Adds some links to handy tools.

---

content/concepts/programs.md

Closes https://github.com/entropyxyz/entropy-docs/issues/113

Updates Programs page with new details for basic questions.

---

content/basics/quickstart.md

Closes https://github.com/entropyxyz/entropy-docs/issues/209

Changes unit8array to base64 string.

---

content/concepts/signing.md

Closes https://github.com/entropyxyz/entropy-docs/issues/112

Adds message size. Adds better intro to signing.

---

content/reference/command-line-interface.md

Closes https://github.com/entropyxyz/entropy-docs/issues/65

Adds basic information for config in CLI reference.

---

content/reference/command-line-interface.md

Closes https://github.com/entropyxyz/entropy-docs/issues/225

Adds log location and information for CLI.

---

content/basics/support.md

Closes https://github.com/entropyxyz/entropy-docs/issues/232

Changes description to lead in front-matter.

---

themes/hextra/layouts/partials/font-toggle.html

Closes https://github.com/entropyxyz/entropy-docs/issues/230

Switches icon to book-open.

---

.github/workflows/pr-preview.yaml

Closes https://github.com/entropyxyz/entropy-docs/issues/82

Adds PR-Preview workflow.

---

content/guides/transfer-funds.md

Depends on https://github.com/entropyxyz/cli/pull/252

Removes mention of account password.

---

content/reference/command-line-interface.md

Closes https://github.com/entropyxyz/entropy-docs/issues/243

Adds explicit callout for Node v20.

---

.github/workflows/pr-preview.yaml

This workflow isn't working right now, and now is not the time to fix it. I'm commenting out this workflow for now so that we can address the issues in the near future.

Comments out PR-Preview workflow

---

content/basics/quickstart.md
content/guides/deploy-a-program.md
content/guides/manage-accounts.md
content/guides/register-an-account.md
content/reference/command-line-interface.md

Closes https://github.com/entropyxyz/entropy-docs/issues/248

Updates CLI to use `entropy tui`.

---

content/guides/register-an-account.md

Updates Register guide to use programmatic CLI.

---

content/reference/rust-testing-interface.md

Closes https://github.com/entropyxyz/entropy-docs/issues/268

Puts OSes into popularity order.

---

.github/PULL_REQUEST_TEMPLATE

Closes https://github.com/entropyxyz/entropy-docs/issues/281

Adds PR template.

---

content/guides/spin-up-a-devnet.md

I was running through the devnet spin up guide and ran into some problems. I started adding _fixes_ to appropriate pages, but now I'm working if they're relevant or if the guide needs and overhaul.

Potential fixes for Devnet spin-up guide.

---

content/concepts/programs.md
content/guides/spin-up-a-devnet.md

Add a simple summary explaining the basics if Entropy Programs.
Closes https://github.com/entropyxyz/entropy-docs/issues/295
https://docs.entropy.xyz/concepts/programs/
None.

Add summary for Programs page.

---

content/concepts/programs.md
content/guides/spin-up-a-devnet.md

Reverts entropyxyz/entropy-docs#296

Revert "Add summary for Programs page."

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

Simplifies issue and PR templates.

---

content/guides/spin-up-a-devnet.md

Closes #310.
- /guides/spin-up-a-devnet/

Simplifies docker steps. Reduces title length.

---

content/guides/use-the-explorer.md

Closes https://github.com/entropyxyz/entropy-docs/issues/305
- https://docs.entropy.xyz/guides/use-the-explorer/

Adds public interface instructions to explorer guide.

---

README.md

Closes https://github.com/entropyxyz/entropy-docs/issues/316
N/a
Updates the README to reflect the available shortcodes.

Adds new shortcodes to README.
